### ISSUE TITLE
Glitchy hill after advanced launch

### ISSUE THREAD

**Issue by AndDan-stack** [neatodev/AsylumLauncher#4]
After launching  Arkham Asylem from the advanced launcher, and changing the resolution from default 720 to 1080, the papers at the bottom of this hill become stretched, distorted and clustered. Fortunately it has no collision, so batman can walk through the  glitch, and
![35140_88](https://github.com/user-attachments/assets/4a85481e-9ed6-4bd6-9ce1-31ea3cecd0e6)
![35140_89](https://github.com/user-attachments/assets/520be015-ff69-48bc-adf0-fe885584055b)
![35140_90](https://github.com/user-attachments/assets/5f611512-8b32-4d19-82ff-18d9d46a01b7)
 up the hill as normal gameplay dictates.

**Comment by neatodev** [comment]
The launcher simply changes the resolution parameters, it does not behave in a way that could cause this in your game. The issue either lies with another mod or it is a random bug you encountered.
